/* =========================================================
 * 🍂 시제 시간여행 (과거 · 현재 · 미래) 데이터
 * - 활동 32개 × 난이도 3단계 (초급 / 중급 / 고급)
 * - 영어 템플릿 :  {원형|과거형}  → 시제에 따라 골라 씀
 *      과거  : "I "     + 과거형   (I played basketball.)
 *      현재  : "I "     + 원형     (I play basketball.)
 *      미래  : "I'll "  + 원형     (I'll play basketball.)
 * - 한글 템플릿 :  {과거|현재|미래}
 * - 규칙(regular) / 불규칙(irregular) 동사 구분 + 규칙 종류(rule)
 * - 때(When)는 시제마다 다르고, 장소 · 누구와는 공통
 *  ※ 교과서 주요 표현 6개 모두 초급에 포함:
 *    played basketball / visited my grandmother / picked watermelons /
 *    made cookies / swam in the sea / went to a festival
 * ========================================================= */

/* ===== 시제 정보 ===== */
const TENSES = {
  past: {
    label: "과거", icon: "⏪", helper: "did",
    question: "What did you do this summer?",
    questionKo: "여름방학에 무엇을 했니?",
    subtitle: "여름방학에 한 일을 영어로 말해 봐요!",
    answerForm: "I + 동사의 과거형",
    example: "I played basketball.",
  },
  present: {
    label: "현재", icon: "⏺", helper: "do",
    question: "What do you do on weekends?",
    questionKo: "주말에 보통 무엇을 하니?",
    subtitle: "평소에 하는 일을 영어로 말해 봐요!",
    answerForm: "I + 동사 원형",
    example: "I play basketball.",
  },
  future: {
    label: "미래", icon: "⏩", helper: "will",
    question: "What will you do this fall?",
    questionKo: "이번 가을에 무엇을 할 거니?",
    subtitle: "앞으로 할 일을 영어로 말해 봐요!",
    answerForm: "I'll(I will) + 동사 원형",
    example: "I'll play basketball.",
  },
};
const TENSE_ORDER = ["past", "present", "future"];

/* ===== 카테고리 ===== */
const CATEGORIES = [
  { key: "make",   label: "🍪 만들기·체험" },
  { key: "active", label: "🏀 운동·배우기" },
  { key: "trip",   label: "🎡 나들이·여행" },
  { key: "home",   label: "🎮 놀이·취미" },
];

/* ===== 규칙 동사 종류 설명 ===== */
const RULES = {
  ed:     { short: "-ed",        desc: "동사 뒤에 -ed 를 붙여요" },
  d:      { short: "-d",         desc: "e 로 끝나면 -d 만 붙여요" },
  ied:    { short: "y → ied",    desc: "자음 + y 로 끝나면 y 를 i 로 바꾸고 -ed" },
  double: { short: "자음 + ed",   desc: "마지막 자음을 한 번 더 쓰고 -ed" },
};

/* ===== 활동 32개 =====
 * verb : [원형, 과거형]     regular : 규칙 동사인지     rule : 규칙 종류
 * place: true → 문장 안에 이미 장소가 있어서 장소 표현을 또 붙이면 어색함
 * base / mid / adv : 초급 / 중급 / 고급 영어 템플릿   (ko* : 한글)
 */
const ACTIVITIES = [
  /* ---------- 🍪 만들기·체험 ---------- */
  { cat: "make", emoji: "🍉", verb: ["pick", "picked"], regular: true, rule: "ed", place: false,
    img: "kids picking watermelons at a farm",
    base: "{pick|picked} watermelons",                                   ko:    "나는 수박을 {땄어|따|딸 거야}.",
    mid:  "{pick|picked} watermelons at the farm",                       koMid: "나는 농장에서 수박을 {땄어|따|딸 거야}.",
    adv:  "{pick|picked} watermelons and {eat|ate} them with my family", koAdv: "나는 수박을 따서 가족과 함께 {먹었어|먹어|먹을 거야}." },
  { cat: "make", emoji: "🍪", verb: ["make", "made"], regular: false, place: false,
    img: "kids baking cookies in a kitchen",
    base: "{make|made} cookies",                                          ko:    "나는 쿠키를 {만들었어|만들어|만들 거야}.",
    mid:  "{make|made} cookies with my mom",                              koMid: "나는 엄마와 쿠키를 {만들었어|만들어|만들 거야}.",
    adv:  "{make|made} cookies and {share|shared} them with my friends",  koAdv: "나는 쿠키를 만들어 친구들과 {나눠 먹었어|나눠 먹어|나눠 먹을 거야}." },
  { cat: "make", emoji: "🍅", verb: ["grow", "grew"], regular: false, place: false,
    img: "growing red tomatoes in a sunny garden",
    base: "{grow|grew} tomatoes",                                         ko:    "나는 토마토를 {길렀어|길러|기를 거야}.",
    mid:  "{grow|grew} tomatoes in the garden",                           koMid: "나는 정원에서 토마토를 {길렀어|길러|기를 거야}.",
    adv:  "{grow|grew} tomatoes and {water|watered} them every morning",  koAdv: "나는 토마토를 기르고 매일 아침 물을 {줬어|줘|줄 거야}." },
  { cat: "make", emoji: "🍞", verb: ["bake", "baked"], regular: true, rule: "d", place: false,
    img: "child baking fresh bread with grandmother",
    base: "{bake|baked} bread",                                           ko:    "나는 빵을 {구웠어|구워|구울 거야}.",
    mid:  "{bake|baked} bread with my grandmother",                       koMid: "나는 할머니와 빵을 {구웠어|구워|구울 거야}.",
    adv:  "{bake|baked} bread and {give|gave} it to my neighbors",        koAdv: "나는 빵을 구워 이웃에게 {나눠 줬어|나눠 줘|나눠 줄 거야}." },
  { cat: "make", emoji: "✏️", verb: ["draw", "drew"], regular: false, place: false,
    img: "child drawing a webtoon comic on a tablet",
    base: "{draw|drew} webtoons",                                         ko:    "나는 웹툰을 {그렸어|그려|그릴 거야}.",
    mid:  "{draw|drew} webtoons on my tablet",                            koMid: "나는 태블릿으로 웹툰을 {그렸어|그려|그릴 거야}.",
    adv:  "{draw|drew} webtoons and {post|posted} them online",           koAdv: "나는 웹툰을 그려서 온라인에 {올렸어|올려|올릴 거야}." },
  { cat: "make", emoji: "🎥", verb: ["make", "made"], regular: false, place: false,
    img: "kids filming a youtube video with a camera",
    base: "{make|made} a YouTube video",                                  ko:    "나는 유튜브 영상을 {만들었어|만들어|만들 거야}.",
    mid:  "{make|made} a YouTube video with my friends",                  koMid: "나는 친구들과 유튜브 영상을 {만들었어|만들어|만들 거야}.",
    adv:  "{make|made} a YouTube video and {show|showed} it to my class", koAdv: "나는 유튜브 영상을 만들어 반 친구들에게 {보여 줬어|보여 줘|보여 줄 거야}." },
  { cat: "make", emoji: "🎨", verb: ["paint", "painted"], regular: true, rule: "ed", place: false,
    img: "child painting a picture of colorful autumn leaves",
    base: "{paint|painted} a picture",                                    ko:    "나는 그림을 {그렸어|그려|그릴 거야}.",
    mid:  "{paint|painted} a picture of autumn leaves",                   koMid: "나는 단풍잎 그림을 {그렸어|그려|그릴 거야}.",
    adv:  "{paint|painted} a picture and {hang|hung} it on the wall",     koAdv: "나는 그림을 그려서 벽에 {걸었어|걸어|걸 거야}." },
  { cat: "make", emoji: "🍜", verb: ["cook", "cooked"], regular: true, rule: "ed", place: false,
    img: "korean ramyeon noodles cooking in a pot",
    base: "{cook|cooked} ramyeon",                                        ko:    "나는 라면을 {끓였어|끓여|끓일 거야}.",
    mid:  "{cook|cooked} ramyeon for my brother",                         koMid: "나는 동생에게 라면을 {끓여 줬어|끓여 줘|끓여 줄 거야}.",
    adv:  "{cook|cooked} ramyeon and {eat|ate} it with kimchi",           koAdv: "나는 라면을 끓여서 김치와 함께 {먹었어|먹어|먹을 거야}." },

  /* ---------- 🏀 운동·배우기 ---------- */
  { cat: "active", emoji: "🏀", verb: ["play", "played"], regular: true, rule: "ed", place: false,
    img: "kids playing basketball on an outdoor court",
    base: "{play|played} basketball",                                     ko:    "나는 농구를 {했어|해|할 거야}.",
    mid:  "{play|played} basketball with my friends",                     koMid: "나는 친구들과 농구를 {했어|해|할 거야}.",
    adv:  "{play|played} basketball and {win|won} the game",              koAdv: "나는 농구를 하고 경기에서 {이겼어|이겨|이길 거야}." },
  { cat: "active", emoji: "🌊", verb: ["swim", "swam"], regular: false, place: true,
    img: "child swimming in the blue sea",
    base: "{swim|swam} in the sea",                                       ko:    "나는 바다에서 {수영했어|수영해|수영할 거야}.",
    mid:  "{swim|swam} in the sea with my family",                        koMid: "나는 가족과 바다에서 {수영했어|수영해|수영할 거야}.",
    adv:  "{swim|swam} in the sea and {build|built} a sandcastle",        koAdv: "나는 바다에서 수영하고 모래성을 {쌓았어|쌓아|쌓을 거야}." },
  { cat: "active", emoji: "🥋", verb: ["learn", "learned"], regular: true, rule: "ed", place: false,
    img: "children practicing taekwondo in white uniforms",
    base: "{learn|learned} taekwondo",                                    ko:    "나는 태권도를 {배웠어|배워|배울 거야}.",
    mid:  "{learn|learned} taekwondo every day",                          koMid: "나는 매일 태권도를 {배웠어|배워|배울 거야}.",
    adv:  "{learn|learned} taekwondo and {get|got} a yellow belt",        koAdv: "나는 태권도를 배워서 노란 띠를 {땄어|따|딸 거야}." },
  { cat: "active", emoji: "🚴", verb: ["ride", "rode"], regular: false, place: false,
    img: "child riding a bicycle on an autumn road",
    base: "{ride|rode} a bike",                                           ko:    "나는 자전거를 {탔어|타|탈 거야}.",
    mid:  "{ride|rode} a bike along the river",                           koMid: "나는 강을 따라 자전거를 {탔어|타|탈 거야}.",
    adv:  "{ride|rode} a bike and {see|saw} the autumn leaves",           koAdv: "나는 자전거를 타며 단풍을 {봤어|봐|볼 거야}." },
  { cat: "active", emoji: "⚽", verb: ["play", "played"], regular: true, rule: "ed", place: false,
    img: "happy kids playing soccer on a green field",
    base: "{play|played} soccer",                                         ko:    "나는 축구를 {했어|해|할 거야}.",
    mid:  "{play|played} soccer at the park",                             koMid: "나는 공원에서 축구를 {했어|해|할 거야}.",
    adv:  "{play|played} soccer and {score|scored} a goal",               koAdv: "나는 축구를 하고 골을 {넣었어|넣어|넣을 거야}." },
  { cat: "active", emoji: "💃", verb: ["dance", "danced"], regular: true, rule: "d", place: false,
    img: "kids dancing kpop dance together",
    base: "{dance|danced} to K-pop",                                      ko:    "나는 케이팝에 맞춰 {춤췄어|춤춰|춤출 거야}.",
    mid:  "{dance|danced} to K-pop with my friends",                      koMid: "나는 친구들과 케이팝에 맞춰 {춤췄어|춤춰|춤출 거야}.",
    adv:  "{dance|danced} to K-pop and {perform|performed} on stage",     koAdv: "나는 케이팝 춤을 추고 무대에서 {공연했어|공연해|공연할 거야}." },
  { cat: "active", emoji: "🏃", verb: ["run", "ran"], regular: false, place: true,
    img: "child running in a park with autumn trees",
    base: "{run|ran} in the park",                                        ko:    "나는 공원에서 {달렸어|달려|달릴 거야}.",
    mid:  "{run|ran} in the park every morning",                          koMid: "나는 매일 아침 공원에서 {달렸어|달려|달릴 거야}.",
    adv:  "{run|ran} in the park and {fly|flew} a kite",                  koAdv: "나는 공원에서 달리고 연을 {날렸어|날려|날릴 거야}." },
  { cat: "active", emoji: "🛼", verb: ["go", "went"], regular: false, place: false,
    img: "child rollerblading in a park",
    base: "{go|went} rollerblading",                                      ko:    "나는 인라인을 {탔어|타|탈 거야}.",
    mid:  "{go|went} rollerblading with my sister",                       koMid: "나는 여동생과 인라인을 {탔어|타|탈 거야}.",
    adv:  "{go|went} rollerblading and {fall|fell} down twice",           koAdv: "나는 인라인을 타다가 두 번 {넘어졌어|넘어져|넘어질 거야}." },

  /* ---------- 🎡 나들이·여행 ---------- */
  { cat: "trip", emoji: "👵", verb: ["visit", "visited"], regular: true, rule: "ed", place: true,
    img: "grandmother smiling and hugging her grandchild",
    base: "{visit|visited} my grandmother",                               ko:    "나는 할머니를 {찾아뵀어|찾아봬|찾아뵐 거야}.",
    mid:  "{visit|visited} my grandmother in the country",                koMid: "나는 시골에 계신 할머니를 {찾아뵀어|찾아봬|찾아뵐 거야}.",
    adv:  "{visit|visited} my grandmother and {help|helped} her on the farm", koAdv: "나는 할머니를 찾아뵙고 농장 일을 {도왔어|도와|도울 거야}." },
  { cat: "trip", emoji: "🎪", verb: ["go", "went"], regular: false, place: true,
    img: "kids enjoying a colorful festival with lanterns and balloons",
    base: "{go|went} to a festival",                                      ko:    "나는 축제에 {갔어|가|갈 거야}.",
    mid:  "{go|went} to a festival with my family",                       koMid: "나는 가족과 축제에 {갔어|가|갈 거야}.",
    adv:  "{go|went} to a festival and {eat|ate} street food",            koAdv: "나는 축제에 가서 길거리 음식을 {먹었어|먹어|먹을 거야}." },
  { cat: "trip", emoji: "🏖️", verb: ["go", "went"], regular: false, place: true,
    img: "kids playing on a sunny sandy beach",
    base: "{go|went} to the beach",                                       ko:    "나는 해변에 {갔어|가|갈 거야}.",
    mid:  "{go|went} to the beach with my friends",                       koMid: "나는 친구들과 해변에 {갔어|가|갈 거야}.",
    adv:  "{go|went} to the beach and {find|found} pretty shells",        koAdv: "나는 해변에 가서 예쁜 조개껍데기를 {찾았어|찾아|찾을 거야}." },
  { cat: "trip", emoji: "🏕️", verb: ["go", "went"], regular: false, place: true,
    img: "family camping with a tent in nature at night",
    base: "{go|went} camping",                                            ko:    "나는 캠핑을 {갔어|가|갈 거야}.",
    mid:  "{go|went} camping in the mountains",                           koMid: "나는 산으로 캠핑을 {갔어|가|갈 거야}.",
    adv:  "{go|went} camping and {see|saw} the stars at night",           koAdv: "나는 캠핑을 가서 밤에 별을 {봤어|봐|볼 거야}." },
  { cat: "trip", emoji: "✈️", verb: ["travel", "traveled"], regular: true, rule: "ed", place: true,
    img: "beautiful Jeju island with blue ocean",
    base: "{travel|traveled} to Jeju",                                    ko:    "나는 제주도로 여행을 {갔어|가|갈 거야}.",
    mid:  "{travel|traveled} to Jeju by plane",                           koMid: "나는 비행기로 제주도에 {갔어|가|갈 거야}.",
    adv:  "{travel|traveled} to Jeju and {climb|climbed} Mt. Halla",      koAdv: "나는 제주도에 가서 한라산에 {올랐어|올라|오를 거야}." },
  { cat: "trip", emoji: "💦", verb: ["go", "went"], regular: false, place: true,
    img: "kids having fun at a water park with big slides",
    base: "{go|went} to a water park",                                    ko:    "나는 워터파크에 {갔어|가|갈 거야}.",
    mid:  "{go|went} to a water park with my cousin",                     koMid: "나는 사촌과 워터파크에 {갔어|가|갈 거야}.",
    adv:  "{go|went} to a water park and {ride|rode} the big slides",     koAdv: "나는 워터파크에 가서 큰 슬라이드를 {탔어|타|탈 거야}." },
  { cat: "trip", emoji: "📸", verb: ["take", "took"], regular: false, place: true,
    img: "friends taking fun photos in a photo booth",
    base: "{take|took} photos at a photo booth",                          ko:    "나는 인생네컷을 {찍었어|찍어|찍을 거야}.",
    mid:  "{take|took} photos at a photo booth with my friends",          koMid: "나는 친구들과 인생네컷을 {찍었어|찍어|찍을 거야}.",
    adv:  "{take|took} photos at a photo booth and {keep|kept} them in my album", koAdv: "나는 인생네컷을 찍어 앨범에 {모아 뒀어|모아 둬|모아 둘 거야}." },
  { cat: "trip", emoji: "🎆", verb: ["see", "saw"], regular: false, place: false,
    img: "colorful fireworks over a river at night",
    base: "{see|saw} fireworks",                                          ko:    "나는 불꽃놀이를 {봤어|봐|볼 거야}.",
    mid:  "{see|saw} fireworks at the river",                             koMid: "나는 강가에서 불꽃놀이를 {봤어|봐|볼 거야}.",
    adv:  "{see|saw} fireworks and {take|took} many pictures",            koAdv: "나는 불꽃놀이를 보고 사진을 많이 {찍었어|찍어|찍을 거야}." },

  /* ---------- 🎮 놀이·취미 ---------- */
  { cat: "home", emoji: "📚", verb: ["read", "read"], regular: false, place: false,
    img: "child reading a stack of books",
    base: "{read|read} many books",                                       ko:    "나는 책을 많이 {읽었어|읽어|읽을 거야}.",
    mid:  "{read|read} many books at the library",                        koMid: "나는 도서관에서 책을 많이 {읽었어|읽어|읽을 거야}.",
    adv:  "{read|read} many books and {write|wrote} book reports",        koAdv: "나는 책을 많이 읽고 독후감을 {썼어|써|쓸 거야}." },
  { cat: "home", emoji: "🎬", verb: ["watch", "watched"], regular: true, rule: "ed", place: false,
    img: "kids watching a movie with popcorn",
    base: "{watch|watched} movies",                                       ko:    "나는 영화를 {봤어|봐|볼 거야}.",
    mid:  "{watch|watched} movies on rainy days",                         koMid: "나는 비 오는 날 영화를 {봤어|봐|볼 거야}.",
    adv:  "{watch|watched} movies and {eat|ate} popcorn with my friends", koAdv: "나는 친구들과 영화를 보며 팝콘을 {먹었어|먹어|먹을 거야}." },
  { cat: "home", emoji: "🎮", verb: ["play", "played"], regular: true, rule: "ed", place: false,
    img: "child playing computer games happily",
    base: "{play|played} computer games",                                 ko:    "나는 컴퓨터 게임을 {했어|해|할 거야}.",
    mid:  "{play|played} computer games after my homework",               koMid: "나는 숙제를 한 뒤에 컴퓨터 게임을 {했어|해|할 거야}.",
    adv:  "{play|played} computer games and {beat|beat} my high score",   koAdv: "나는 컴퓨터 게임을 해서 최고 점수를 {깼어|깨|깰 거야}." },
  { cat: "home", emoji: "🍢", verb: ["eat", "ate"], regular: false, place: false,
    img: "korean tteokbokki spicy rice cakes",
    base: "{eat|ate} tteokbokki",                                         ko:    "나는 떡볶이를 {먹었어|먹어|먹을 거야}.",
    mid:  "{eat|ate} tteokbokki with my friends",                         koMid: "나는 친구들과 떡볶이를 {먹었어|먹어|먹을 거야}.",
    adv:  "{eat|ate} tteokbokki and {drink|drank} cold water",            koAdv: "나는 떡볶이를 먹고 찬물을 {마셨어|마셔|마실 거야}." },
  { cat: "home", emoji: "🎤", verb: ["sing", "sang"], regular: false, place: true,
    img: "kids singing at a karaoke singing room with microphones",
    base: "{sing|sang} at a singing room",                                ko:    "나는 노래방에서 {노래했어|노래해|노래할 거야}.",
    mid:  "{sing|sang} at a singing room with my friends",                koMid: "나는 친구들과 노래방에서 {노래했어|노래해|노래할 거야}.",
    adv:  "{sing|sang} at a singing room and {dance|danced} with my friends", koAdv: "나는 노래방에서 노래하고 친구들과 {춤췄어|춤춰|춤출 거야}." },
  { cat: "home", emoji: "🍧", verb: ["eat", "ate"], regular: false, place: false,
    img: "korean shaved ice dessert bingsu with fruit",
    base: "{eat|ate} bingsu",                                             ko:    "나는 빙수를 {먹었어|먹어|먹을 거야}.",
    mid:  "{eat|ate} bingsu on hot days",                                 koMid: "나는 더운 날 빙수를 {먹었어|먹어|먹을 거야}.",
    adv:  "{eat|ate} bingsu and {feel|felt} cool",                        koAdv: "나는 빙수를 먹고 {시원해졌어|시원해져|시원해질 거야}." },
  { cat: "home", emoji: "📺", verb: ["watch", "watched"], regular: true, rule: "ed", place: false,
    img: "child watching youtube on a tablet",
    base: "{watch|watched} YouTube",                                      ko:    "나는 유튜브를 {봤어|봐|볼 거야}.",
    mid:  "{watch|watched} YouTube in my room",                           koMid: "나는 내 방에서 유튜브를 {봤어|봐|볼 거야}.",
    adv:  "{watch|watched} YouTube and {learn|learned} fun science tricks", koAdv: "나는 유튜브를 보며 재미있는 과학 실험을 {배웠어|배워|배울 거야}." },
  { cat: "home", emoji: "🛌", verb: ["have", "had"], regular: false, place: true,
    img: "kids having a fun sleepover with pillows",
    base: "{have|had} a sleepover",                                       ko:    "나는 친구 집에서 {잤어|자|잘 거야}.",
    mid:  "{have|had} a sleepover at my friend's house",                  koMid: "나는 친구 집에서 자고 {왔어|와|올 거야}.",
    adv:  "{have|had} a sleepover and {stay|stayed} up late with my friends", koAdv: "나는 친구 집에서 자며 친구들과 늦게까지 {놀았어|놀아|놀 거야}." },
];

/* ===== 동사 변화표 보너스 (활동에는 없지만 꼭 알아야 할 동사) ===== */
const BONUS_VERBS = [
  { verb: ["do", "did"],       regular: false, meaning: "하다" },
  { verb: ["get", "got"],      regular: false, meaning: "얻다, 받다" },
  { verb: ["come", "came"],    regular: false, meaning: "오다" },
  { verb: ["buy", "bought"],   regular: false, meaning: "사다" },
  { verb: ["meet", "met"],     regular: false, meaning: "만나다" },
  { verb: ["study", "studied"], regular: true, rule: "ied", meaning: "공부하다" },
  { verb: ["cry", "cried"],    regular: true, rule: "ied", meaning: "울다" },
  { verb: ["stop", "stopped"], regular: true, rule: "double", meaning: "멈추다" },
  { verb: ["plan", "planned"], regular: true, rule: "double", meaning: "계획하다" },
  { verb: ["help", "helped"],  regular: true, rule: "ed", meaning: "돕다" },
  { verb: ["clean", "cleaned"], regular: true, rule: "ed", meaning: "청소하다" },
  { verb: ["like", "liked"],   regular: true, rule: "d", meaning: "좋아하다" },
];

/* 동사 원형의 뜻 (변화표 카드에 표시) */
const VERB_MEANINGS = {
  pick: "따다, 고르다", make: "만들다", grow: "기르다", bake: "굽다", draw: "그리다",
  paint: "(물감으로) 그리다", cook: "요리하다", play: "(운동·게임을) 하다, 놀다",
  swim: "수영하다", learn: "배우다", ride: "타다", dance: "춤추다", run: "달리다",
  go: "가다", visit: "방문하다", travel: "여행하다", take: "(사진을) 찍다",
  see: "보다", read: "읽다", watch: "보다", eat: "먹다", sing: "노래하다", have: "가지다, (파티·행사를) 하다",
};

/* ===== 때 (When) — 시제마다 다름 ===== */
const TIME_EXPRESSIONS = {
  past: [
    { en: "yesterday",           ko: "어제",          emoji: "📆" },
    { en: "last weekend",        ko: "지난 주말에",   emoji: "🗓️" },
    { en: "last week",           ko: "지난주에",      emoji: "📅" },
    { en: "last summer",         ko: "지난여름에",    emoji: "☀️" },
    { en: "during the vacation", ko: "방학 동안",     emoji: "🏝️" },
    { en: "two days ago",        ko: "이틀 전에",     emoji: "⏳" },
    { en: "last night",          ko: "어젯밤에",      emoji: "🌙" },
    { en: "on Chuseok",          ko: "추석에",        emoji: "🌕" },
  ],
  present: [
    { en: "every day",       ko: "매일",          emoji: "📆" },
    { en: "every morning",   ko: "매일 아침",     emoji: "🌅" },
    { en: "every weekend",   ko: "주말마다",      emoji: "🗓️" },
    { en: "after school",    ko: "방과 후에",     emoji: "🏫" },
    { en: "on rainy days",   ko: "비 오는 날에",  emoji: "🌧️" },
    { en: "in the evening",  ko: "저녁에",        emoji: "🌆" },
    { en: "at night",        ko: "밤에",          emoji: "🌙" },
    { en: "on Sundays",      ko: "일요일마다",    emoji: "⛪" },
  ],
  future: [
    { en: "tomorrow",        ko: "내일",          emoji: "📆" },
    { en: "this weekend",    ko: "이번 주말에",   emoji: "🗓️" },
    { en: "next week",       ko: "다음 주에",     emoji: "📅" },
    { en: "this fall",       ko: "이번 가을에",   emoji: "🍂" },
    { en: "on Chuseok",      ko: "추석에",        emoji: "🌕" },
    { en: "after school",    ko: "방과 후에",     emoji: "🏫" },
    { en: "this winter",     ko: "이번 겨울에",   emoji: "⛄" },
    { en: "next Sunday",     ko: "다음 주 일요일에", emoji: "⛪" },
  ],
};

/* ===== 장소 (Where) — 공통 ===== */
const PLACE_EXPRESSIONS = [
  { en: "at the park",           ko: "공원에서",      emoji: "🌳" },
  { en: "at the farm",           ko: "농장에서",      emoji: "🚜" },
  { en: "at the beach",          ko: "해변에서",      emoji: "🏖️" },
  { en: "at the playground",     ko: "놀이터에서",    emoji: "🛝" },
  { en: "at school",             ko: "학교에서",      emoji: "🏫" },
  { en: "at the gym",            ko: "체육관에서",    emoji: "🏟️" },
  { en: "at the library",        ko: "도서관에서",    emoji: "📖" },
  { en: "at a cafe",             ko: "카페에서",      emoji: "☕" },
  { en: "at home",               ko: "집에서",        emoji: "🏠" },
  { en: "in my room",            ko: "내 방에서",     emoji: "🛏️" },
  { en: "at my friend's house",  ko: "친구 집에서",   emoji: "🏡" },
  { en: "in the mountains",      ko: "산에서",        emoji: "⛰️" },
];

/* ===== 누구와 (With whom) — 공통 ===== */
const WITH_EXPRESSIONS = [
  { en: "with my friends",     ko: "친구들과",  emoji: "👯" },
  { en: "with my family",      ko: "가족과",    emoji: "👨‍👩‍👧‍👦" },
  { en: "with my mom",         ko: "엄마와",    emoji: "👩" },
  { en: "with my dad",         ko: "아빠와",    emoji: "👨" },
  { en: "with my grandmother", ko: "할머니와",  emoji: "👵" },
  { en: "with my brother",     ko: "형이랑",    emoji: "👦" },
  { en: "with my sister",      ko: "여동생과",  emoji: "👧" },
  { en: "with my cousin",      ko: "사촌과",    emoji: "🧒" },
];

/* ===== 문장 만들기용 때·장소·누구와 (짧은 목록) ===== */
const BUILD_WHEN = {
  past: [
    { en: "yesterday",           ko: "어제" },
    { en: "last weekend",        ko: "지난 주말에" },
    { en: "last summer",         ko: "지난여름에" },
    { en: "during the vacation", ko: "방학 동안" },
    { en: "two days ago",        ko: "이틀 전에" },
    { en: "on Chuseok",          ko: "추석에" },
  ],
  present: [
    { en: "every day",       ko: "매일" },
    { en: "every morning",   ko: "매일 아침" },
    { en: "on weekends",     ko: "주말마다" },
    { en: "after school",    ko: "방과 후에" },
    { en: "in the evening",  ko: "저녁에" },
    { en: "on Sundays",      ko: "일요일마다" },
  ],
  future: [
    { en: "tomorrow",        ko: "내일" },
    { en: "this weekend",    ko: "이번 주말에" },
    { en: "next week",       ko: "다음 주에" },
    { en: "this fall",       ko: "이번 가을에" },
    { en: "on Chuseok",      ko: "추석에" },
    { en: "after school",    ko: "방과 후에" },
  ],
};

const BUILD_WHERE = [
  { en: "at the park",    ko: "공원에서" },
  { en: "at home",        ko: "집에서" },
  { en: "in my room",     ko: "내 방에서" },
  { en: "at the library", ko: "도서관에서" },
  { en: "at school",      ko: "학교에서" },
  { en: "at the gym",     ko: "체육관에서" },
];

const BUILD_WITH = [
  { en: "with my friends",     ko: "친구들과" },
  { en: "with my family",      ko: "가족과" },
  { en: "with my mom",         ko: "엄마와" },
  { en: "with my dad",         ko: "아빠와" },
  { en: "with my grandmother", ko: "할머니와" },
  { en: "with my cousin",      ko: "사촌과" },
];

/* ===== 단어 뜻 사전 ===== */
function wordKey(w) {
  return w.toLowerCase().replace(/^[^a-z']+/, "").replace(/[^a-z']+$/, "");
}

const WORD_MEANINGS = {
  /* 주어 · 조동사 · 질문 */
  "i": "나는",
  "i'll": "나는 ~할 거야 (I will)",
  "will": "~할 것이다 (미래)",
  "did": "do 의 과거형 (불규칙) — ~했다",
  "do": "하다",
  "what": "무엇",
  "you": "너, 너희",
  "this": "이, 이번",
  "summer": "여름",
  "fall": "가을; 넘어지다",
  "weekends": "주말마다",
  "weekend": "주말",
  "vacation": "방학",

  /* 활동 동사 — 원형 */
  "pick": "따다, 고르다",
  "make": "만들다",
  "grow": "기르다, 키우다",
  "bake": "(빵·과자를) 굽다",
  "draw": "(그림을) 그리다",
  "paint": "(물감으로) 그리다, 칠하다",
  "cook": "요리하다, 끓이다",
  "play": "(운동·게임을) 하다, 놀다",
  "swim": "수영하다",
  "learn": "배우다",
  "ride": "타다",
  "dance": "춤추다; 춤",
  "run": "달리다",
  "go": "가다",
  "visit": "방문하다, 찾아뵙다",
  "travel": "여행하다",
  "take": "(사진을) 찍다, 가져가다",
  "see": "보다",
  "read": "읽다 (과거형도 read — 발음은 '레드')",
  "watch": "보다, 지켜보다",
  "eat": "먹다",
  "sing": "노래하다",
  "have": "가지다; (파티·행사를) 하다",

  /* 활동 동사 — 과거형 */
  "picked": "pick 의 과거형 (규칙 -ed) — 땄다",
  "made": "make 의 과거형 (불규칙) — 만들었다",
  "grew": "grow 의 과거형 (불규칙) — 길렀다",
  "baked": "bake 의 과거형 (규칙 -d) — 구웠다",
  "drew": "draw 의 과거형 (불규칙) — 그렸다",
  "painted": "paint 의 과거형 (규칙 -ed) — 그렸다",
  "cooked": "cook 의 과거형 (규칙 -ed) — 요리했다",
  "played": "play 의 과거형 (규칙 -ed) — 했다, 놀았다",
  "swam": "swim 의 과거형 (불규칙) — 수영했다",
  "learned": "learn 의 과거형 (규칙 -ed) — 배웠다",
  "rode": "ride 의 과거형 (불규칙) — 탔다",
  "danced": "dance 의 과거형 (규칙 -d) — 춤췄다",
  "ran": "run 의 과거형 (불규칙) — 달렸다",
  "went": "go 의 과거형 (불규칙) — 갔다",
  "visited": "visit 의 과거형 (규칙 -ed) — 방문했다",
  "traveled": "travel 의 과거형 (규칙 -ed) — 여행했다",
  "took": "take 의 과거형 (불규칙) — 찍었다",
  "saw": "see 의 과거형 (불규칙) — 봤다",
  "watched": "watch 의 과거형 (규칙 -ed) — 봤다",
  "ate": "eat 의 과거형 (불규칙) — 먹었다",
  "sang": "sing 의 과거형 (불규칙) — 노래했다",
  "had": "have 의 과거형 (불규칙) — 가졌다, 했다",

  /* 고급 문장의 두 번째 동사 */
  "share": "나누다", "shared": "share 의 과거형 (규칙 -d) — 나눴다",
  "water": "물; 물을 주다", "watered": "water 의 과거형 (규칙 -ed) — 물을 줬다",
  "give": "주다", "gave": "give 의 과거형 (불규칙) — 줬다",
  "post": "(인터넷에) 올리다", "posted": "post 의 과거형 (규칙 -ed) — 올렸다",
  "show": "보여주다", "showed": "show 의 과거형 (규칙 -ed) — 보여줬다",
  "hang": "걸다", "hung": "hang 의 과거형 (불규칙) — 걸었다",
  "win": "이기다", "won": "win 의 과거형 (불규칙) — 이겼다",
  "build": "쌓다, 짓다", "built": "build 의 과거형 (불규칙) — 쌓았다",
  "get": "얻다, 받다", "got": "get 의 과거형 (불규칙) — 받았다",
  "score": "점수; 득점하다", "scored": "score 의 과거형 (규칙 -d) — 득점했다",
  "perform": "공연하다", "performed": "perform 의 과거형 (규칙 -ed) — 공연했다",
  "fly": "날리다, 날다", "flew": "fly 의 과거형 (불규칙) — 날렸다",
  "fell": "fall 의 과거형 (불규칙) — 넘어졌다",
  "help": "돕다", "helped": "help 의 과거형 (규칙 -ed) — 도왔다",
  "find": "찾다", "found": "find 의 과거형 (불규칙) — 찾았다",
  "climb": "오르다", "climbed": "climb 의 과거형 (규칙 -ed) — 올랐다",
  "keep": "보관하다, 간직하다", "kept": "keep 의 과거형 (불규칙) — 간직했다",
  "write": "쓰다", "wrote": "write 의 과거형 (불규칙) — 썼다",
  "beat": "이기다, (기록을) 깨다 (과거형도 beat)",
  "drink": "마시다", "drank": "drink 의 과거형 (불규칙) — 마셨다",
  "feel": "느끼다", "felt": "feel 의 과거형 (불규칙) — 느꼈다",
  "stay": "머무르다", "stayed": "stay 의 과거형 (규칙 -ed) — 머물렀다",

  /* 명사 · 기타 */
  "watermelons": "수박 (여러 개)",
  "cookies": "쿠키 (여러 개)",
  "tomatoes": "토마토 (여러 개)",
  "bread": "빵",
  "webtoons": "웹툰",
  "youtube": "유튜브",
  "video": "영상, 동영상",
  "picture": "그림, 사진",
  "pictures": "사진들, 그림들",
  "ramyeon": "라면",
  "kimchi": "김치",
  "basketball": "농구",
  "sea": "바다",
  "taekwondo": "태권도",
  "bike": "자전거",
  "soccer": "축구",
  "k-pop": "케이팝 (K-pop)",
  "rollerblading": "인라인스케이트 타기",
  "grandmother": "할머니",
  "festival": "축제",
  "beach": "해변, 바닷가",
  "camping": "캠핑",
  "jeju": "제주(도)",
  "water": "물; (water park) 워터파크",
  "park": "공원, ~파크",
  "photos": "사진들",
  "photo": "사진",
  "booth": "부스, 작은 공간",
  "fireworks": "불꽃놀이",
  "books": "책 (여러 권)",
  "movies": "영화 (여러 편)",
  "computer": "컴퓨터",
  "games": "게임 (여러 개)",
  "tteokbokki": "떡볶이",
  "singing": "노래 부르기 (singing room: 노래방)",
  "room": "방, ~방",
  "bingsu": "빙수",
  "sleepover": "친구 집에서 자고 노는 것",
  "farm": "농장",
  "garden": "정원, 텃밭",
  "tablet": "태블릿",
  "online": "온라인에, 인터넷에",
  "class": "반, 학급",
  "autumn": "가을",
  "leaves": "나뭇잎들 (단풍)",
  "wall": "벽",
  "brother": "형, 오빠, 남동생",
  "sister": "여동생, 누나, 언니",
  "friends": "친구들",
  "friend's": "친구의",
  "family": "가족",
  "mom": "엄마",
  "dad": "아빠",
  "cousin": "사촌",
  "neighbors": "이웃들",
  "game": "경기, 게임",
  "sandcastle": "모래성",
  "yellow": "노란",
  "belt": "띠, 벨트",
  "river": "강",
  "goal": "골, 목표",
  "stage": "무대",
  "kite": "연",
  "twice": "두 번",
  "down": "아래로 (fall down: 넘어지다)",
  "country": "시골, 나라",
  "street": "거리, 길거리",
  "food": "음식",
  "pretty": "예쁜",
  "shells": "조개껍데기들",
  "mountains": "산",
  "stars": "별들",
  "night": "밤",
  "plane": "비행기",
  "mt.": "~산 (mountain)",
  "halla": "한라(산)",
  "big": "큰",
  "slides": "미끄럼틀, 슬라이드",
  "album": "앨범, 사진첩",
  "many": "많은",
  "library": "도서관",
  "book": "책",
  "reports": "보고서, 독후감",
  "rainy": "비가 오는",
  "days": "날들",
  "popcorn": "팝콘",
  "homework": "숙제",
  "high": "높은 (high score: 최고 점수)",
  "cold": "차가운, 추운",
  "hot": "더운, 뜨거운",
  "cool": "시원한; 멋진",
  "fun": "재미있는; 재미",
  "science": "과학",
  "tricks": "기술, 묘기",
  "house": "집",
  "home": "집, 집에",
  "late": "늦게",
  "up": "(stay up) 안 자고 깨어 있다",
  "morning": "아침",
  "every": "매~, 모든",
  "day": "날, 하루",
  "school": "학교",
  "gym": "체육관",
  "playground": "놀이터",
  "cafe": "카페",
  "evening": "저녁",
  "sundays": "일요일마다",
  "sunday": "일요일",
  "yesterday": "어제",
  "last": "지난",
  "week": "주",
  "during": "~동안",
  "two": "둘, 2",
  "ago": "~전에",
  "chuseok": "추석",
  "tomorrow": "내일",
  "next": "다음",
  "winter": "겨울",
  "after": "~후에",

  /* 작은 단어 */
  "a": "하나의", "an": "하나의", "the": "그 (특정한 것)",
  "to": "~에, ~으로", "in": "~안에, ~에", "at": "~에서, ~에", "on": "~에, ~위에",
  "of": "~의", "for": "~을 위해", "with": "~와 함께", "by": "~로, ~을 타고",
  "along": "~을 따라", "and": "그리고", "my": "나의", "her": "그녀를, 그녀의",
  "it": "그것", "them": "그것들을", "me": "나를", "myself": "나 자신, 혼자서",
};
