/* =========================================================
 * 📝 하루 한 장 학습지 데이터
 * - 워드 학습지 "5학년 · 7단원 ENGLISH WORKSHEET" (학습지 1~3, 앞/뒷면) 를
 *   하루 한 면(Day 1 ~ Day 6) 으로 옮긴 것
 * - verbs   : [뜻, 현재형, 과거형]  → 각각 세 번씩 써 보기
 * - fill    : 그림 보고 과거형으로 문장 완성  { ko, before, after, base, past, full, fullKo }
 * ========================================================= */
const WORKSHEET_DAYS = [
  {
    day: 1, sheet: "학습지 1 · 앞면", kind: "regular",
    title: "규칙형: 현재 → 과거", subtitle: "지난 일을 말할 때, 동사의 끝부분을 규칙에 따라 바꾸어요.",
    rules: [
      { label: "대부분은 -ed", ex: "play → played" },
      { label: "e로 끝나면 -d", ex: "bake → baked" },
      { label: "hug는 g를 한 번 더!", ex: "hug → hugged" },
    ],
    verbs: [
      ["참가하다", "join", "joined"],
      ["보다", "watch", "watched"],
      ["방문하다", "visit", "visited"],
      ["배우다", "learn", "learned"],
      ["놀다 / 경기하다", "play", "played"],
      ["따다 / 수확하다", "pick", "picked"],
      ["(빵·과자를) 굽다", "bake", "baked"],
      ["껴안다", "hug", "hugged"],
    ],
    fill: [
      { ko: "농구를 하다",     before: "I", after: "basketball.",  base: "play", past: "played", fullKo: "나는 농구를 했어.", art: "basketball" },
      { ko: "수박을 수확하다", before: "I", after: "watermelons.", base: "pick", past: "picked", fullKo: "나는 수박을 땄어.", art: "watermelon" },
      { ko: "쿠키를 굽다",     before: "I", after: "cookies.",     base: "bake", past: "baked",  fullKo: "나는 쿠키를 구웠어.", art: "cookies" },
      { ko: "할머니를 껴안다", before: "I", after: "my grandma.",  base: "hug",  past: "hugged", fullKo: "나는 할머니를 껴안았어.", art: "grandmother" },
    ],
  },
  {
    day: 2, sheet: "학습지 1 · 뒷면", kind: "irregular",
    title: "불규칙형: 현재 → 과거", subtitle: "-ed만 붙여 만들 수 없어요. 현재형과 과거형을 한 쌍으로 익혀요.",
    note: "have → had, come → came처럼 모양이 많이 달라지는 동사도 있어요.",
    verbs: [
      ["가지다", "have", "had"],
      ["오다", "come", "came"],
      ["얻다 / 받다", "get", "got"],
      ["달리다", "run", "ran"],
      ["앉다", "sit", "sat"],
      ["서다", "stand", "stood"],
      ["가다", "go", "went"],
      ["하다", "do", "did"],
      ["만들다", "make", "made"],
    ],
    fill: [
      { ko: "학교에 오다",  before: "I", after: "to school.",    base: "come", past: "came", fullKo: "나는 학교에 왔어.", emoji: "🏫" },
      { ko: "의자에 앉다",  before: "I", after: "on the chair.", base: "sit",  past: "sat",  fullKo: "나는 의자에 앉았어.", emoji: "🪑" },
      { ko: "빨리 달리다",  before: "I", after: "fast.",         base: "run",  past: "ran",  fullKo: "나는 빨리 달렸어.", art: "runpark" },
    ],
  },
  {
    day: 3, sheet: "학습지 2 · 앞면", kind: "regular",
    title: "규칙형: 현재 → 과거", subtitle: "지난 일을 말할 때, 동사의 끝부분을 규칙에 따라 바꾸어요.",
    rules: [
      { label: "대부분은 -ed", ex: "walk → walked" },
      { label: "e로 끝나면 -d", ex: "close → closed" },
      { label: "stop은 p를 한 번 더!", ex: "stop → stopped" },
    ],
    verbs: [
      ["걷다", "walk", "walked"],
      ["말하다", "talk", "talked"],
      ["돕다", "help", "helped"],
      ["씻다", "wash", "washed"],
      ["청소하다", "clean", "cleaned"],
      ["요리하다", "cook", "cooked"],
      ["열다", "open", "opened"],
      ["닫다", "close", "closed"],
    ],
    fill: [
      { ko: "공원에서 걷다", before: "I", after: "in the park.",    base: "walk", past: "walked", fullKo: "나는 공원에서 걸었어.", art: "runpark" },
      { ko: "친구와 말하다", before: "I", after: "with my friend.", base: "talk", past: "talked", fullKo: "나는 친구와 이야기했어.", emoji: "🗣️" },
      { ko: "손을 씻다",     before: "I", after: "my hands.",       base: "wash", past: "washed", fullKo: "나는 손을 씻었어.", emoji: "🧼" },
      { ko: "문을 열다",     before: "I", after: "the door.",       base: "open", past: "opened", fullKo: "나는 문을 열었어.", emoji: "🚪" },
    ],
  },
  {
    day: 4, sheet: "학습지 2 · 뒷면", kind: "irregular",
    title: "불규칙형: 현재 → 과거", subtitle: "-ed만 붙여 만들 수 없어요. 현재형과 과거형을 한 쌍으로 익혀요.",
    note: "read → read: 철자는 같지만, 현재형과 과거형의 소리가 달라요. (현재 '리드', 과거 '레드')",
    verbs: [
      ["보다", "see", "saw"],
      ["자다", "sleep", "slept"],
      ["마시다", "drink", "drank"],
      ["먹다", "eat", "ate"],
      ["노래하다", "sing", "sang"],
      ["주다", "give", "gave"],
      ["가져가다", "take", "took"],
      ["말하다", "say", "said"],
      ["읽다", "read", "read"],
    ],
    fill: [
      { ko: "우유를 마시다", before: "I", after: "milk.",    base: "drink", past: "drank", fullKo: "나는 우유를 마셨어.", emoji: "🥛" },
      { ko: "점심을 먹다",   before: "I", after: "lunch.",   base: "eat",   past: "ate",   fullKo: "나는 점심을 먹었어.", emoji: "🍱" },
      { ko: "책을 읽다",     before: "I", after: "a book.",  base: "read",  past: "read",  fullKo: "나는 책을 읽었어.", art: "books" },
    ],
  },
  {
    day: 5, sheet: "학습지 3 · 앞면", kind: "regular",
    title: "규칙형: 현재 → 과거", subtitle: "지난 일을 말할 때, 동사의 끝부분을 규칙에 따라 바꾸어요.",
    rules: [
      { label: "대부분은 -ed", ex: "look → looked" },
      { label: "자음 + y: y를 i로 바꾸고 -ed", ex: "study → studied" },
      { label: "stop은 p를 한 번 더!", ex: "stop → stopped" },
    ],
    verbs: [
      ["보다", "look", "looked"],
      ["듣다", "listen", "listened"],
      ["원하다", "want", "wanted"],
      ["좋아하다", "like", "liked"],
      ["사용하다", "use", "used"],
      ["춤추다", "dance", "danced"],
      ["공부하다", "study", "studied"],
      ["멈추다", "stop", "stopped"],
    ],
    fill: [
      { ko: "음악을 듣다",     before: "I", after: "to music.",     base: "listen", past: "listened", fullKo: "나는 음악을 들었어.", emoji: "🎧" },
      { ko: "춤추다",          before: "I", after: "",              base: "dance",  past: "danced",   fullKo: "나는 춤을 췄어.", art: "kpop" },
      { ko: "영어를 공부하다", before: "I", after: "English.",      base: "study",  past: "studied",  fullKo: "나는 영어를 공부했어.", emoji: "📖" },
      { ko: "자전거를 멈추다", before: "I", after: "the bicycle.",  base: "stop",   past: "stopped",  fullKo: "나는 자전거를 멈췄어.", art: "bike" },
    ],
  },
  {
    day: 6, sheet: "학습지 3 · 뒷면", kind: "irregular",
    title: "불규칙형: 현재 → 과거", subtitle: "-ed만 붙여 만들 수 없어요. 현재형과 과거형을 한 쌍으로 익혀요.",
    note: "put → put처럼 현재형과 과거형의 철자가 같은 동사도 있어요.",
    verbs: [
      ["가르치다", "teach", "taught"],
      ["기르다", "grow", "grew"],
      ["수영하다", "swim", "swam"],
      ["사다", "buy", "bought"],
      ["타다", "ride", "rode"],
      ["쓰다", "write", "wrote"],
      ["그리다", "draw", "drew"],
      ["만나다", "meet", "met"],
      ["놓다", "put", "put"],
    ],
    fill: [
      { ko: "수영장에서 수영하다", before: "I", after: "in the pool.", base: "swim",  past: "swam",  fullKo: "나는 수영장에서 수영했어.", art: "sea" },
      { ko: "과일을 사다",         before: "I", after: "fruit.",       base: "buy",   past: "bought", fullKo: "나는 과일을 샀어.", emoji: "🍎" },
      { ko: "편지를 쓰다",         before: "I", after: "a letter.",    base: "write", past: "wrote", fullKo: "나는 편지를 썼어.", emoji: "✉️" },
    ],
  },
];

/* 학습지에만 나오는 단어 뜻 (단어 풍선용) */
Object.assign(WORD_MEANINGS, {
  "join": "참가하다", "joined": "join 의 과거형 (규칙 -ed) — 참가했다",
  "hug": "껴안다", "hugged": "hug 의 과거형 (규칙, g 한 번 더 + ed) — 껴안았다",
  "grandma": "할머니",
  "come": "오다", "came": "come 의 과거형 (불규칙) — 왔다",
  "sit": "앉다", "sat": "sit 의 과거형 (불규칙) — 앉았다",
  "stand": "서다", "stood": "stand 의 과거형 (불규칙) — 섰다",
  "chair": "의자", "fast": "빨리",
  "walk": "걷다", "walked": "walk 의 과거형 (규칙 -ed) — 걸었다",
  "talk": "말하다, 이야기하다", "talked": "talk 의 과거형 (규칙 -ed) — 이야기했다",
  "wash": "씻다", "washed": "wash 의 과거형 (규칙 -ed) — 씻었다",
  "clean": "청소하다", "cleaned": "clean 의 과거형 (규칙 -ed) — 청소했다",
  "open": "열다", "opened": "open 의 과거형 (규칙 -ed) — 열었다",
  "close": "닫다", "closed": "close 의 과거형 (규칙 -d) — 닫았다",
  "hands": "손 (두 손)", "door": "문", "friend": "친구",
  "sleep": "자다", "slept": "sleep 의 과거형 (불규칙) — 잤다",
  "say": "말하다", "said": "say 의 과거형 (불규칙) — 말했다",
  "milk": "우유", "lunch": "점심",
  "look": "보다", "looked": "look 의 과거형 (규칙 -ed) — 봤다",
  "listen": "듣다", "listened": "listen 의 과거형 (규칙 -ed) — 들었다",
  "want": "원하다", "wanted": "want 의 과거형 (규칙 -ed) — 원했다",
  "like": "좋아하다", "liked": "like 의 과거형 (규칙 -d) — 좋아했다",
  "use": "사용하다", "used": "use 의 과거형 (규칙 -d) — 사용했다",
  "study": "공부하다", "studied": "study 의 과거형 (규칙, y → ied) — 공부했다",
  "stop": "멈추다", "stopped": "stop 의 과거형 (규칙, p 한 번 더 + ed) — 멈췄다",
  "music": "음악", "english": "영어", "bicycle": "자전거",
  "teach": "가르치다", "taught": "teach 의 과거형 (불규칙) — 가르쳤다",
  "buy": "사다", "bought": "buy 의 과거형 (불규칙) — 샀다",
  "meet": "만나다", "met": "meet 의 과거형 (불규칙) — 만났다",
  "put": "놓다 (과거형도 put)",
  "pool": "수영장", "fruit": "과일", "letter": "편지",
});
